services:
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
      - "./rabbitmq:/etc/ballcom/"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_CONFIG_FILE=/etc/ballcom/rabbitmq.conf
    networks:
      - rabbitmq_net

  mariadb:
    image: mariadb
    container_name: mariadb
    volumes:
      - mariadbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: username
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"

  customer-management:
    image: ballcom/customer-management
    build: CustomerManagement
    depends_on:
      - mariadb
      - rabbitmq
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://*:5000
    networks:
      - rabbitmq_net

  inventory-management:
    image: ballcom/inventory-management
    build: InventoryManagement
    depends_on:
      - mariadb
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_URLS=http://*:5001
    networks:
      - rabbitmq_net

  notification-service:
    image: ballcom/notification-service
    build: NotificationService
    ports:
      - "5002:5002"
    environment:
      - ASPNETCORE_URLS=http://*:5002
    networks:
      - rabbitmq_net

  order-management:
    image: ballcom/order-management
    build: OrderManagement
    depends_on:
      - mariadb
    ports:
      - "5003:5003"
    environment:
      - ASPNETCORE_URLS=http://*:5003
    networks:
      - rabbitmq_net

  orderpicker:
    image: ballcom/orderpicker
    build: Orderpicker
    depends_on:
      - mariadb
    ports:
      - "5004:5004"
    environment:
      - ASPNETCORE_URLS=http://*:5004
    networks:
      - rabbitmq_net
  
  payment-service:
    image: ballcom/payment-service
    build: PaymentService
    depends_on:
      - mariadb
    ports:
      - "5005:5005"
    environment:
      - ASPNETCORE_URLS=http://*:5005
    networks:
      - rabbitmq_net

  service-desk:
    image: ballcom/service-desk
    build: ServiceDesk
    depends_on:
      - mariadb
    ports:
      - "5006:5006"
    environment:
      - ASPNETCORE_URLS=http://*:5006
    networks:
      - rabbitmq_net

  supplier-management:
    image: ballcom/supplier-management
    build: SupplierManagement
    depends_on:
      - mariadb
    ports:
      - "5007:5007"
    environment:
      - ASPNETCORE_URLS=http://*:5007
    networks:
      - rabbitmq_net

  transport-management:
    image: ballcom/transport-management
    build: TransportManagement
    depends_on:
      - mariadb
    ports:
      - "5008:5008"
    environment:
      - ASPNETCORE_URLS=http://*:5008
    networks:
      - rabbitmq_net

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mariadb
      PMA_PORT: 3306
    links:
      - mariadb

volumes:  
  rabbitmqdata:
    external: true
  mariadbdata:
    external: true
    
networks:
  rabbitmq_net:
      driver: bridge